### PR TITLE
feat: Add fill done drawable

### PR DESCRIPTION
**Pull request by Mrey3000**

### CODE REVIEW

**Comment by Mrey3000** [comment]
Add step done drawble
image

**Comment by loukwn** [comment]
Hello @Mrey3000 sorry I just noticed your PR. Can you tell me your use case and why this change is needed? Can you not achieve what you want with the current implementation? 

Thanks a lot for the PR!

**Comment by loukwn** [comment]
Actually is it to provide a different kind of drawable for the thumbs that are already completed? As in your screenshot the one in the right was visited first so it is "done" , the one in the center is the one being visited now so is in progress and it has a different drawable and the one on the left is not visited at all?

If so, this library assumes that all "visited"  thumbs are filled and the rest are unfilled. I do not think a solution to add an "done" kind of thumb type is appropriate to me.

What I could do is add a way to provide custom drawables for filled thumbs by either providing a list or something similar. 

I will put some thought in to it!

**Comment by loukwn** [comment]
@Mrey3000  Sorry for taking a while on this. I started doing a general refactor but that turned out to be a big job for now (probably will plan it for a 2.0.0 release). For now I just added an `activeThumb` property both in the Compose and the View versions that represents the last filled stage/thumb so you can customize it properly and it also changes nicely during animations too. Will ship with the 1.2.0 release quite soon!

I will close this PR as it is unneeded, but thanks a lot for taking the time to open this! Do let me know if you need anything else feature wise and I will try to accomodate!

**Pull request closed without merging**
